// Hand-written to mirror `supabase gen types typescript` output, generated by
// introspecting the live project (ykkgzqeicyqfglvnzrri) via scripts/db-full-schema.mjs.
// Regenerate with the Supabase CLI once Docker is available:
//   npx supabase gen types typescript --db-url "$DATABASE_URL" > types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string
          role: Database["public"]["Enums"]["user_role"]
          first_name: string
          last_name: string
          email: string
          phone: string | null
          professional_title: string | null
          institution: string | null
          department: string | null
          country: string | null
          orcid: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          role?: Database["public"]["Enums"]["user_role"]
          first_name: string
          last_name: string
          email: string
          phone?: string | null
          professional_title?: string | null
          institution?: string | null
          department?: string | null
          country?: string | null
          orcid?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          role?: Database["public"]["Enums"]["user_role"]
          first_name?: string
          last_name?: string
          email?: string
          phone?: string | null
          professional_title?: string | null
          institution?: string | null
          department?: string | null
          country?: string | null
          orcid?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      conferences: {
        Row: {
          id: string
          name: string
          short_name: string
          theme: string | null
          reference_prefix: string
          location: string
          venue: string | null
          start_date: string | null
          end_date: string | null
          early_submission_deadline: string | null
          late_submission_deadline: string | null
          review_deadline: string | null
          decision_date: string | null
          abstract_word_limit: number
          max_file_size_mb: number
          allowed_file_types: string[]
          presentation_types: string[]
          blind_review_mode: Database["public"]["Enums"]["blind_mode"]
          is_active: boolean
          submissions_open: boolean
          secretariat_email: string | null
          website: string | null
          ref_sequence: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          short_name: string
          theme?: string | null
          reference_prefix: string
          location: string
          venue?: string | null
          start_date?: string | null
          end_date?: string | null
          early_submission_deadline?: string | null
          late_submission_deadline?: string | null
          review_deadline?: string | null
          decision_date?: string | null
          abstract_word_limit?: number
          max_file_size_mb?: number
          allowed_file_types?: string[]
          presentation_types?: string[]
          blind_review_mode?: Database["public"]["Enums"]["blind_mode"]
          is_active?: boolean
          submissions_open?: boolean
          secretariat_email?: string | null
          website?: string | null
          ref_sequence?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          short_name?: string
          theme?: string | null
          reference_prefix?: string
          location?: string
          venue?: string | null
          start_date?: string | null
          end_date?: string | null
          early_submission_deadline?: string | null
          late_submission_deadline?: string | null
          review_deadline?: string | null
          decision_date?: string | null
          abstract_word_limit?: number
          max_file_size_mb?: number
          allowed_file_types?: string[]
          presentation_types?: string[]
          blind_review_mode?: Database["public"]["Enums"]["blind_mode"]
          is_active?: boolean
          submissions_open?: boolean
          secretariat_email?: string | null
          website?: string | null
          ref_sequence?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      conference_subthemes: {
        Row: {
          id: string
          conference_id: string
          name: string
          description: string | null
          sort_order: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          conference_id: string
          name: string
          description?: string | null
          sort_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          conference_id?: string
          name?: string
          description?: string | null
          sort_order?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "conference_subthemes_conference_id_fkey"
            columns: ["conference_id"]
            isOneToOne: false
            referencedRelation: "conferences"
            referencedColumns: ["id"]
          },
        ]
      }
      reviewer_profiles: {
        Row: {
          id: string
          user_id: string
          conference_id: string
          subtheme_id: string | null
          expertise: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          conference_id: string
          subtheme_id?: string | null
          expertise?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          conference_id?: string
          subtheme_id?: string | null
          expertise?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "reviewer_profiles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviewer_profiles_conference_id_fkey"
            columns: ["conference_id"]
            isOneToOne: false
            referencedRelation: "conferences"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviewer_profiles_subtheme_id_fkey"
            columns: ["subtheme_id"]
            isOneToOne: false
            referencedRelation: "conference_subthemes"
            referencedColumns: ["id"]
          },
        ]
      }
      committee_members: {
        Row: {
          id: string
          user_id: string
          conference_id: string
          title: string | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          conference_id: string
          title?: string | null
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          conference_id?: string
          title?: string | null
          is_active?: boolean
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "committee_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "committee_members_conference_id_fkey"
            columns: ["conference_id"]
            isOneToOne: false
            referencedRelation: "conferences"
            referencedColumns: ["id"]
          },
        ]
      }
      submissions: {
        Row: {
          id: string
          conference_id: string
          corresponding_author_id: string
          subtheme_id: string | null
          reference_number: string | null
          title: string
          keywords: string[] | null
          presentation_preference: Database["public"]["Enums"]["presentation_preference"]
          status: Database["public"]["Enums"]["submission_status"]
          current_version: number
          no_conflict_of_interest: boolean
          ethical_approval_obtained: boolean
          funding_declaration: string | null
          originality_confirmed: boolean
          screening_notes: string | null
          screened_by: string | null
          screened_at: string | null
          submitted_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          conference_id: string
          corresponding_author_id: string
          subtheme_id?: string | null
          reference_number?: string | null
          title?: string
          keywords?: string[] | null
          presentation_preference?: Database["public"]["Enums"]["presentation_preference"]
          status?: Database["public"]["Enums"]["submission_status"]
          current_version?: number
          no_conflict_of_interest?: boolean
          ethical_approval_obtained?: boolean
          funding_declaration?: string | null
          originality_confirmed?: boolean
          screening_notes?: string | null
          screened_by?: string | null
          screened_at?: string | null
          submitted_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          conference_id?: string
          corresponding_author_id?: string
          subtheme_id?: string | null
          reference_number?: string | null
          title?: string
          keywords?: string[] | null
          presentation_preference?: Database["public"]["Enums"]["presentation_preference"]
          status?: Database["public"]["Enums"]["submission_status"]
          current_version?: number
          no_conflict_of_interest?: boolean
          ethical_approval_obtained?: boolean
          funding_declaration?: string | null
          originality_confirmed?: boolean
          screening_notes?: string | null
          screened_by?: string | null
          screened_at?: string | null
          submitted_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "submissions_conference_id_fkey"
            columns: ["conference_id"]
            isOneToOne: false
            referencedRelation: "conferences"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "submissions_corresponding_author_id_fkey"
            columns: ["corresponding_author_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "submissions_subtheme_id_fkey"
            columns: ["subtheme_id"]
            isOneToOne: false
            referencedRelation: "conference_subthemes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "submissions_screened_by_fkey"
            columns: ["screened_by"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      submission_versions: {
        Row: {
          id: string
          submission_id: string
          version_number: number
          abstract_text: string
          word_count: number
          change_summary: string | null
          submitted_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          submission_id: string
          version_number: number
          abstract_text?: string
          word_count?: number
          change_summary?: string | null
          submitted_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          submission_id?: string
          version_number?: number
          abstract_text?: string
          word_count?: number
          change_summary?: string | null
          submitted_at?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "submission_versions_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      submission_authors: {
        Row: {
          id: string
          submission_id: string
          author_order: number
          is_corresponding: boolean
          first_name: string
          last_name: string
          email: string
          institution: string | null
          department: string | null
          country: string | null
          orcid: string | null
          created_at: string
        }
        Insert: {
          id?: string
          submission_id: string
          author_order: number
          is_corresponding?: boolean
          first_name: string
          last_name: string
          email: string
          institution?: string | null
          department?: string | null
          country?: string | null
          orcid?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          submission_id?: string
          author_order?: number
          is_corresponding?: boolean
          first_name?: string
          last_name?: string
          email?: string
          institution?: string | null
          department?: string | null
          country?: string | null
          orcid?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "submission_authors_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      submission_documents: {
        Row: {
          id: string
          submission_id: string
          version_number: number
          storage_path: string
          file_name: string
          file_type: string
          file_size_bytes: number
          is_current: boolean
          uploaded_by: string
          uploaded_at: string
        }
        Insert: {
          id?: string
          submission_id: string
          version_number?: number
          storage_path: string
          file_name: string
          file_type: string
          file_size_bytes: number
          is_current?: boolean
          uploaded_by: string
          uploaded_at?: string
        }
        Update: {
          id?: string
          submission_id?: string
          version_number?: number
          storage_path?: string
          file_name?: string
          file_type?: string
          file_size_bytes?: number
          is_current?: boolean
          uploaded_by?: string
          uploaded_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "submission_documents_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "submissions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "submission_documents_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      review_assignments: {
        Row: {
          id: string
          submission_id: string
          reviewer_id: string
          conference_id: string
          assigned_by: string | null
          status: Database["public"]["Enums"]["review_status"]
          due_date: string | null
          assigned_at: string
          accepted_at: string | null
          completed_at: string | null
          conflict_declared_at: string | null
          conflict_reason: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          submission_id: string
          reviewer_id: string
          conference_id: string
          assigned_by?: string | null
          status?: Database["public"]["Enums"]["review_status"]
          due_date?: string | null
          assigned_at?: string
          accepted_at?: string | null
          completed_at?: string | null
          conflict_declared_at?: string | null
          conflict_reason?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          submission_id?: string
          reviewer_id?: string
          conference_id?: string
          assigned_by?: string | null
          status?: Database["public"]["Enums"]["review_status"]
          due_date?: string | null
          assigned_at?: string
          accepted_at?: string | null
          completed_at?: string | null
          conflict_declared_at?: string | null
          conflict_reason?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "review_assignments_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "submissions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "review_assignments_reviewer_id_fkey"
            columns: ["reviewer_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "review_assignments_conference_id_fkey"
            columns: ["conference_id"]
            isOneToOne: false
            referencedRelation: "conferences"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "review_assignments_assigned_by_fkey"
            columns: ["assigned_by"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      reviews: {
        Row: {
          id: string
          assignment_id: string
          submission_id: string
          reviewer_id: string
          score_originality: number | null
          score_relevance: number | null
          score_methodology: number | null
          score_clarity: number | null
          score_significance: number | null
          average_score: number | null
          recommendation: Database["public"]["Enums"]["decision_type"] | null
          comments_to_committee: string | null
          comments_to_author: string | null
          is_submitted: boolean
          submitted_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          assignment_id: string
          submission_id: string
          reviewer_id: string
          score_originality?: number | null
          score_relevance?: number | null
          score_methodology?: number | null
          score_clarity?: number | null
          score_significance?: number | null
          average_score?: number | null
          recommendation?: Database["public"]["Enums"]["decision_type"] | null
          comments_to_committee?: string | null
          comments_to_author?: string | null
          is_submitted?: boolean
          submitted_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          assignment_id?: string
          submission_id?: string
          reviewer_id?: string
          score_originality?: number | null
          score_relevance?: number | null
          score_methodology?: number | null
          score_clarity?: number | null
          score_significance?: number | null
          average_score?: number | null
          recommendation?: Database["public"]["Enums"]["decision_type"] | null
          comments_to_committee?: string | null
          comments_to_author?: string | null
          is_submitted?: boolean
          submitted_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "reviews_assignment_id_fkey"
            columns: ["assignment_id"]
            isOneToOne: false
            referencedRelation: "review_assignments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "submissions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_reviewer_id_fkey"
            columns: ["reviewer_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      decisions: {
        Row: {
          id: string
          submission_id: string
          conference_id: string
          decided_by: string
          decision: Database["public"]["Enums"]["decision_type"]
          decision_notes: string | null
          author_message: string | null
          revision_deadline: string | null
          is_final: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          submission_id: string
          conference_id: string
          decided_by: string
          decision: Database["public"]["Enums"]["decision_type"]
          decision_notes?: string | null
          author_message?: string | null
          revision_deadline?: string | null
          is_final?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          submission_id?: string
          conference_id?: string
          decided_by?: string
          decision?: Database["public"]["Enums"]["decision_type"]
          decision_notes?: string | null
          author_message?: string | null
          revision_deadline?: string | null
          is_final?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "decisions_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "submissions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "decisions_conference_id_fkey"
            columns: ["conference_id"]
            isOneToOne: false
            referencedRelation: "conferences"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "decisions_decided_by_fkey"
            columns: ["decided_by"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          id: string
          submission_id: string | null
          recipient_id: string
          recipient_email: string
          notification_type: string
          subject: string
          status: Database["public"]["Enums"]["notification_status"]
          sent_at: string | null
          error_message: string | null
          retry_count: number
          resend_message_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          submission_id?: string | null
          recipient_id: string
          recipient_email: string
          notification_type: string
          subject: string
          status?: Database["public"]["Enums"]["notification_status"]
          sent_at?: string | null
          error_message?: string | null
          retry_count?: number
          resend_message_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          submission_id?: string | null
          recipient_id?: string
          recipient_email?: string
          notification_type?: string
          subject?: string
          status?: Database["public"]["Enums"]["notification_status"]
          sent_at?: string | null
          error_message?: string | null
          retry_count?: number
          resend_message_id?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "submissions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_recipient_id_fkey"
            columns: ["recipient_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_logs: {
        Row: {
          id: string
          actor_id: string | null
          actor_email: string | null
          action: string
          entity_type: string
          entity_id: string | null
          previous_status: string | null
          new_status: string | null
          metadata: Json | null
          ip_address: string | null
          created_at: string
        }
        Insert: {
          id?: string
          actor_id?: string | null
          actor_email?: string | null
          action: string
          entity_type: string
          entity_id?: string | null
          previous_status?: string | null
          new_status?: string | null
          metadata?: Json | null
          ip_address?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          actor_id?: string | null
          actor_email?: string | null
          action?: string
          entity_type?: string
          entity_id?: string | null
          previous_status?: string | null
          new_status?: string | null
          metadata?: Json | null
          ip_address?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "user_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: Record<string, never>
    Functions: {
      auth_has_role: {
        Args: { required_role: Database["public"]["Enums"]["user_role"] }
        Returns: boolean
      }
      auth_user_role: {
        Args: Record<string, never>
        Returns: Database["public"]["Enums"]["user_role"]
      }
      generate_reference_number: {
        Args: { p_conference_id: string }
        Returns: string
      }
    }
    Enums: {
      blind_mode: "none" | "single" | "double"
      decision_type:
        | "accepted"
        | "accepted_oral"
        | "accepted_poster"
        | "minor_revision"
        | "major_revision"
        | "rejected"
      notification_status: "pending" | "sent" | "failed"
      presentation_preference: "oral" | "poster" | "either"
      review_status: "pending" | "in_progress" | "completed" | "conflict"
      submission_status:
        | "draft"
        | "submitted"
        | "screening"
        | "assigned"
        | "under_review"
        | "reviews_completed"
        | "decision_pending"
        | "revision_required"
        | "accepted"
        | "accepted_oral"
        | "accepted_poster"
        | "rejected"
        | "withdrawn"
      user_role: "author" | "reviewer" | "committee" | "admin" | "super_admin"
    }
  }
}
